/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "outer-space": "#36393E",
        aquamarine: "#B5FFE9",
        "mint-green": "#C5E0D8",
        silver: "#C9C9C9",
        "tea-rose": "#CEABB1",
        gray: "#616161",
        void: "#313338",
        cream: "#EEF0FD",
        "night-1": "#4D4D4D",
        "night-2": "#414141",
        "night-3": "#333333",
        "night-4": "#666666",
        "dark-primary": "#BB86FC",
        "dark-primary-variant": "#3700B3",
        "dark-secondary": "#03DAC6",
        "dark-background": "#121212",
        "dark-background-01dp": "#1E1E1E",
        "dark-background-03dp": "#232323",
        "dark-background-12dp": "#323232",
        "dark-error": "#CF6679",
        "light-primary": "#6200EE",
        "light-primary-variant": "#3700B3",
        "light-secondary": "#03DAC6",
        "light-secondary-variant": "#018786",
        "light-background-1": "#FFFFFF",
        "light-background-2": "#F8F8F8",
        "light-background-3": "#F0F0F0",
        "light-background-4": "#E8E8E8",
        "light-error": "#B00020",
      },
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        raleway: ["Raleway", "sans-serif"],
      },
      aspectRatio: {
        "4/3": "4 / 3",
        "5/4": "5 / 4",
      },
    },
  },
  plugins: [],
  darkMode: "class",
};
